# Generated by Django 5.2.1 on 2026-04-12 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflineJobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=20)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("processed_user_count", models.PositiveIntegerField(default=0)),
                ("summary", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecommendationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("hot", "Hot"),
                            ("itemcf", "ItemCF"),
                            ("usercf", "UserCF"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField()),
                ("top_k", models.PositiveIntegerField(default=20)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecommendationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                ("score", models.FloatField(default=0.0)),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.book"
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="recommendations.recommendationresult",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="SimilarBookResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("rank", models.PositiveIntegerField()),
                (
                    "source_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_source",
                        to="catalog.book",
                    ),
                ),
                (
                    "target_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_target",
                        to="catalog.book",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
    ]
