# Generated by Django 5.2.1 on 2026-04-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_book_average_rating_and_more"),
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recommendationitem",
            constraint=models.UniqueConstraint(
                fields=("result", "rank"), name="unique_recommendation_item_rank"
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendationitem",
            constraint=models.UniqueConstraint(
                fields=("result", "book"), name="unique_recommendation_item_book"
            ),
        ),
        migrations.AddConstraint(
            model_name="similarbookresult",
            constraint=models.UniqueConstraint(
                fields=("source_book", "rank"), name="unique_similar_book_rank"
            ),
        ),
        migrations.AddConstraint(
            model_name="similarbookresult",
            constraint=models.UniqueConstraint(
                fields=("source_book", "target_book"), name="unique_similar_book_target"
            ),
        ),
    ]
