# Generated by Django 5.2.1 on 2026-04-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_average_rating_and_more'),
        ('recommendations', '0002_recommendationitem_unique_recommendation_item_rank_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recommendationitem',
            name='unique_recommendation_item_rank',
        ),
        migrations.RemoveConstraint(
            model_name='recommendationitem',
            name='unique_recommendation_item_book',
        ),
        migrations.RemoveConstraint(
            model_name='similarbookresult',
            name='unique_similar_book_rank',
        ),
        migrations.RemoveConstraint(
            model_name='similarbookresult',
            name='unique_similar_book_target',
        ),
        migrations.AddConstraint(
            model_name='recommendationitem',
            constraint=models.UniqueConstraint(fields=('result', 'rank'), name='unique_recommendation_result_rank'),
        ),
        migrations.AddConstraint(
            model_name='recommendationitem',
            constraint=models.UniqueConstraint(fields=('result', 'book'), name='unique_recommendation_result_book'),
        ),
        migrations.AddConstraint(
            model_name='similarbookresult',
            constraint=models.UniqueConstraint(fields=('source_book', 'rank'), name='unique_similar_book_source_rank'),
        ),
        migrations.AddConstraint(
            model_name='similarbookresult',
            constraint=models.UniqueConstraint(fields=('source_book', 'target_book'), name='unique_similar_book_source_target'),
        ),
    ]
