# Generated by Django 5.2.1 on 2026-04-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EvaluationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experiment_name", models.CharField(max_length=100)),
                ("strategy", models.CharField(max_length=20)),
                ("dataset_name", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("metric_summary", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
