# Generated by Django 5.2.1 on 2026-04-12 19:11

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_book_average_rating_and_more"),
        ("ratings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrating",
            name="score",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="userratinghistory",
            name="score",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="userrating",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 1), ("score__lte", 5)),
                name="user_rating_score_1_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="userratinghistory",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 1), ("score__lte", 5)),
                name="user_rating_history_score_1_5",
            ),
        ),
    ]
