# Generated by Django 5.2.1 on 2026-04-13 15:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_average_rating_and_more'),
        ('ratings', '0002_alter_userrating_score_alter_userratinghistory_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(default='goodbooks-10k', max_length=100)),
                ('dataset_user_id', models.PositiveIntegerField()),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_interactions', to='catalog.book')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dataset_name', 'dataset_user_id', 'book'), name='unique_imported_interaction_dataset_user_book'), models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='imported_interaction_score_1_5')],
            },
        ),
    ]
