# Generated by Django 5.2.1 on 2026-04-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("cover_url", models.URLField(blank=True)),
                ("description", models.TextField()),
                ("publisher", models.CharField(blank=True, max_length=255)),
                (
                    "publication_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("average_rating", models.FloatField(default=0.0)),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="books",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
