# Generated by Django 5.2.1 on 2026-04-12 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="average_rating",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="book",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("average_rating__gte", 0), ("average_rating__lte", 5)
                ),
                name="book_average_rating_0_5",
            ),
        ),
    ]
